
ARG BASEIMAGE_VERSION=edge
ARG CKAN_VERSION=2.9.7
FROM ghcr.io/tum-gis/ckan-sddi-base:${BASEIMAGE_VERSION}

USER root

ADD https://raw.githubusercontent.com/ckan/ckan/ckan-2.9.7/dev-requirements.txt /dev-requirements.txt
RUN set -ex && \
  pip install -r /dev-requirements.txt && \
  rm /dev-requirements.txt

RUN set -ex && \
  ckan config-tool "${CKAN_INI}" "debug = True"

USER ckan
