ARG BASEIMAGE_REPOSITORY=ghcr.io/tum-gis/ckan-sddi
ARG BASEIMAGE_VERSION=edge
ARG CKAN_VERSION=2.9.7

FROM ${BASEIMAGE_REPOSITORY}:${BASEIMAGE_VERSION}

USER root

ADD https://raw.githubusercontent.com/ckan/ckan/ckan-${CKAN_VERSION}/dev-requirements.txt /dev-requirements.txt
RUN set -ex && \
  pip install -r /dev-requirements.txt && \
  rm /dev-requirements.txt

RUN set -ex && \
  ckan config-tool "${CKAN_INI}" "debug = True"

USER ckan
