ARG BASEIMAGE_REPOSITORY=ghcr.io/it-at-m/ckan-sddi-urban
ARG BASEIMAGE_VERSION=edge-2.9.9

FROM ${BASEIMAGE_REPOSITORY}:${BASEIMAGE_VERSION}

ARG CKAN_VERSION=2.9.9
ENV CKAN_VERSION=${CKAN_VERSION}

USER root

ADD https://raw.githubusercontent.com/ckan/ckan/ckan-${CKAN_VERSION}/dev-requirements.txt /dev-requirements.txt
RUN set -ex && \
  pip install -r /dev-requirements.txt && \
  rm /dev-requirements.txt

RUN set -ex && \
  ckan config-tool "${CKAN_INI}" "debug = True"

USER ckan
