name: Cleanup dev images of merged PRs

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM UTC
  workflow_dispatch: # Allows manual triggering

env:
  PACKAGE_NAME: ckan-sddi-dev

jobs:

  cleanup-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          package: ${{ env.PACKAGE_NAME }}
          delete-tags: "^([a-zA-Z0-9-]+-pr-)([0-9]+)"
          use-regex: true
          validate: true
          log-level: debug
