name: Build/push devel image

on:
  push:
    branches: [devel]
    paths:
      - sddi-base/**
      - sddi/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ['sddi-base', 'sddi']
      fail-fast: true
      max-parallel: 1
    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for devel docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/ckan-${{ matrix.context }}
          tags: |
            type=ref,enable=true,event=branch
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-sddi-base-docker-devel
            org.opencontainers.image.documentation=https://github.com/tum-gis/ckan-docker

      - name: Build and publish ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/ckan-${{ matrix.context }}:devel
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=devel

      - name: Extract metadata (tags, labels) for devel-debug docker image
        id: meta-debug
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/ckan-${{ matrix.context }}
          tags: |
            type=ref,enable=true,event=branch,suffix=-debug
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-sddi-base-docker-devel-debug

      - name: Build and publish ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/ckan-${{ matrix.context }}:devel-debug
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile.debug
          push: true
          tags: ${{ steps.meta-debug.outputs.tags }}
          labels: ${{ steps.meta-debug.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=devel
