name: Build/push dev Docker images

on:
  pull_request:
    paths:
      - sddi-base/**
      - sddi/**
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Pull Request Number"
        required: true
        default: "0"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ckan-sddi-dev

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ["sddi-base", "sddi"]
      fail-fast: true
      max-parallel: 1
    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
      - name: Parse short sha
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}
          tags: |
            # Latest tag for PR, PR number only
            type=ref,event=pr,prefix=${{ matrix.context }}-pr-
            # Tag for with commit sha appended
            type=ref,event=pr,prefix=${{ matrix.context }}-pr-,suffix=-{{sha}}
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-${{ matrix.context }}-docker-dev
            org.opencontainers.image.documentation=https://github.com/tum-gis/ckan-docker
      - name: Build and publish ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Print image names
        run: |
          echo "${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}"
          echo "${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}"
      - name: Extract metadata (tags, labels) for docker image
        id: meta-debug
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}
          tags: |
            # Latest tag for PR, PR number only
            type=ref,event=pr,prefix=${{ matrix.context }}-pr-,suffix=-debug
            # Tag for with commit sha appended
            type=ref,event=pr,prefix=${{ matrix.context }}-pr-,suffix=-{{sha}}-debug
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-${{ matrix.context }}-docker-dev-debug
            org.opencontainers.image.documentation=https://github.com/tum-gis/ckan-docker
      - name: Build and publish ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}-debug
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile.debug
          tags: ${{ steps.meta-debug.outputs.tags }}
          labels: ${{ steps.meta-debug.outputs.labels }}
          build-args: |
            BASEIMAGE_REPOSITORY=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}
            BASEIMAGE_VERSION=${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}
      - name: Print image names
        run: |
          echo "${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}-debug"
          echo "${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}-debug"
