name: Build/push dev Docker images

on:
  pull_request:
    # paths:
    #   - sddi-base/**
    #   - sddi/**
    #   - sddi-social/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ['sddi-base', 'sddi', 'sddi-social']
      fail-fast: true
      max-parallel: 1
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Parse short sha
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Log in to the Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev
          tags: |
            type=ref,event=pr,prefix=${{ matrix.context }}-,suffix=-{{sha}}
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-sddi-docker-dev
      -
        name: Build and publish ${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ matrix.context }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}
      -
        name: Print image name
        run: |
          echo "${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}"
      -
        name: Extract metadata (tags, labels) for docker image
        id: meta-debug
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev
          tags: |
            type=ref,event=pr,prefix=${{ matrix.context }}-,suffix=-{{sha}}-debug
          labels: |
            maintainer=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.vendor=Chair of Geoinformatics, Technical University of Munich (TUM)
            org.opencontainers.image.title=ckan-sddi-docker-dev
      -
        name: Build and publish ${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}-debug
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile.debug
          tags: ${{ steps.meta-debug.outputs.tags }}
          labels: ${{ steps.meta-debug.outputs.labels }}
          build-args: |
            BASEIMAGE_VERSION=${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}
      -
        name: Print image name
        run: |
          echo "${{ env.REGISTRY }}/tum-gis/ckan-sddi-dev:${{ matrix.context }}-pr-${{github.event.number}}-${{ steps.short-sha.outputs.sha }}-debug"
